ccflags-y += -Idrivers/media/platform/msm/camera_pd2006
ccflags-y += -Idrivers/media/platform/msm/camera_pd2006/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_pd2006/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
