ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += icp_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_icp_subdev.o cam_icp_context.o hfi.o
