ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_core/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_utils/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_sync/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_req_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_cdm/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_cpas/include/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_jpeg/jpeg_hw/include/

obj-$(CONFIG_SPECTRA_CAMERA) += jpeg_enc_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += jpeg_dma_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_jpeg_hw_mgr.o
