ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_fd
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_fd/fd_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -Idrivers/media/platform/msm/camera_legacy
ccflags-y += -Idrivers/media/platform/msm/camera_legacy/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += fd_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_fd_hw_mgr.o
